sudo: required

language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - clang
            - cmake

            
matrix:
    exclude:
        - os: osx
          compiler: gcc

before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo apt-get install libboost-all-dev;
      fi
  
install:
    # g++
    - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi
    
before_script:  
    - mkdir build
    - cd build
    - cmake ..

script:
    - make -j 3
