sudo: required

language: cpp

compiler:
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
        packages:
            - g++-4.8
            - boost1.55
    
install:
    # g++4.8
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    
before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make
