sudo: required

language: cpp

compiler:
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8


before_install:
    - sudo add-apt-repository -y ppa:boost-latest/ppa
    - sudo apt-get update -y -qq
    - sudo apt-get install -y -qq boost1.55
  
install:
    # g++4.8
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    
before_script:  
    - mkdir build
    - cd build
    - cmake ..

script:
    - make -j 3
